CREATE TABLE [dbo].[mission] (
    [mission_id]                    BIGINT           IDENTITY (1, 1) NOT NULL,
    [mission_title]                 VARCHAR (128)    NOT NULL,
    [mission_short_description]     VARCHAR (256)    NOT NULL,
    [mission_description]           VARCHAR (2048)   NOT NULL,
    [country]                       VARCHAR (50)     NOT NULL,
    [city]                          VARCHAR (50)     NOT NULL,
    [mission_organisation_name]     VARCHAR (50)     NOT NULL,
    [mission_organisation_detail]   VARCHAR (2048)   NOT NULL,
    [mission_start_date]            DATE             NOT NULL,
    [mission_end_date]              DATE             NOT NULL,
    [mission_type]                  VARCHAR (10)     NOT NULL,
    [total_seats]                   BIGINT           NULL,
    [mission_rating]                INT              DEFAULT ((0)) NULL,
    [mission_rating_count]          BIGINT           DEFAULT ((0)) NULL,
    [mission_registration_deadline] DATE             NULL,
    [mission_theme]                 VARCHAR (20)     NOT NULL,
    [mission_skills]                VARCHAR (20)     NULL,
    [mission_availability]          VARCHAR (10)     NOT NULL,
    [mission_video]                 VARBINARY (2048) NULL,
    [created_at]                    DATETIME         DEFAULT (getdate()) NOT NULL,
    [updated_at]                    DATETIME         NULL,
    [deleted_at]                    DATETIME         NULL,
    [status]                        INT              DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([mission_id] ASC),
    CHECK ([mission_availability]='Week-end' OR [mission_availability]='Weekly' OR [mission_availability]='Daily'),
    CHECK ([mission_type]='Time' OR [mission_type]='Goal')
);

